"""Python client SDK for the adsefid.com SMS Web Service API (doc v1.12.0)."""

from .async_client import AdsefidAsyncClient
from .client import AdsefidClient
from .config import SDK_VERSION, ClientConfig
from .enums import (
    LineSelector,
    TemplateParameterType,
    TemplateState,
    WebServiceMessageStatus,
    WebServiceResponseCode,
)
from .exceptions import (
    AdsefidApiError,
    AdsefidError,
    AdsefidRateLimitError,
    AdsefidTransportError,
    AdsefidValidationError,
    AdsefidWebhookVerificationError,
)
from .models.common import (
    CancelledMessageItem,
    CancelResult,
    StatusReceptor,
    StatusResult,
    TemplateParameterValue,
)
from .models.messenger import (
    CancelMessengerRequest,
    MessengerBulkReceptor,
    MessengerBulkReceptorResult,
    MessengerP2pReceptor,
    MessengerP2pReceptorResult,
    SendBulkMessengerRequest,
    SendBulkMessengerResult,
    SendP2pMessengerRequest,
    SendP2pMessengerResult,
    SendSingleMessengerRequest,
    SendSingleMessengerResult,
    SendTemplateMessengerRequest,
    SendTemplateMessengerResult,
    UploadMessengerFileResult,
)
from .models.sms import (
    BulkReceptor,
    BulkReceptorResult,
    CancelSmsRequest,
    GetReceivedSmsResult,
    P2pMessage,
    P2pMessageResult,
    ReceivedSmsMessage,
    SendBulkSmsRequest,
    SendBulkSmsResult,
    SendP2pSmsRequest,
    SendP2pSmsResult,
    SendSingleSmsRequest,
    SendSingleSmsResult,
    SendTemplateSmsRequest,
    SendTemplateSmsResult,
)
from .models.user import AccountInfo, GetUserTemplatesResult, UserLine, UserProfile, UserTemplate
from .webhooks import (
    MessengerStatusWebhookEvent,
    ReceiveWebhookEvent,
    ReceiveWebhookItem,
    StatusWebhookEvent,
    StatusWebhookItem,
    WebhookEvent,
    WebhookEventType,
    WebhookHeaders,
    verify_and_parse_webhook,
)

__version__ = SDK_VERSION

__all__ = [
    "__version__",
    "AdsefidClient",
    "AdsefidAsyncClient",
    "ClientConfig",
    "LineSelector",
    "TemplateParameterType",
    "TemplateParameterValue",
    "TemplateState",
    "WebServiceMessageStatus",
    "WebServiceResponseCode",
    # SMS models
    "SendSingleSmsRequest",
    "SendSingleSmsResult",
    "BulkReceptor",
    "BulkReceptorResult",
    "SendBulkSmsRequest",
    "SendBulkSmsResult",
    "P2pMessage",
    "P2pMessageResult",
    "SendP2pSmsRequest",
    "SendP2pSmsResult",
    "SendTemplateSmsRequest",
    "SendTemplateSmsResult",
    "CancelSmsRequest",
    "ReceivedSmsMessage",
    "GetReceivedSmsResult",
    # Messenger models
    "SendSingleMessengerRequest",
    "SendSingleMessengerResult",
    "MessengerBulkReceptor",
    "MessengerBulkReceptorResult",
    "SendBulkMessengerRequest",
    "SendBulkMessengerResult",
    "MessengerP2pReceptor",
    "MessengerP2pReceptorResult",
    "SendP2pMessengerRequest",
    "SendP2pMessengerResult",
    "SendTemplateMessengerRequest",
    "SendTemplateMessengerResult",
    "UploadMessengerFileResult",
    "CancelMessengerRequest",
    # Shared and user models
    "CancelledMessageItem",
    "CancelResult",
    "StatusReceptor",
    "StatusResult",
    "AccountInfo",
    "UserLine",
    "UserProfile",
    "UserTemplate",
    "GetUserTemplatesResult",
    "AdsefidError",
    "AdsefidValidationError",
    "AdsefidApiError",
    "AdsefidRateLimitError",
    "AdsefidTransportError",
    "AdsefidWebhookVerificationError",
    "MessengerStatusWebhookEvent",
    "ReceiveWebhookEvent",
    "ReceiveWebhookItem",
    "StatusWebhookEvent",
    "StatusWebhookItem",
    "WebhookEvent",
    "WebhookEventType",
    "WebhookHeaders",
    "verify_and_parse_webhook",
]
